---
name: LockedItem
version: 6.0.0
api: 5.0.1
main: ytbjero\LockedItem\LockedItem
author: ytbjero
commands:
  setlock:
    description: Lock the item in your hand
    usage: /setlock
    permission: lockeditem.setlock
  unlock:
    description: Unlock the item in your hand
    usage: /unlock
    permission: lockeditem.unlock
permissions:
  lockeditem.setlock:
    description: Lock the item in your hand
    default: op
  lockeditem.unlock:
    description: Unlock the item in your hand
    default: op
...
